site_name: is-a.dev Docs

theme:
  name: material
  favicon: img/favicon.ico
  logo: img/banner.png
  palette: 
    - scheme: default
      toggle:
        icon: material/toggle-switch 
        name: Switch to dark mode
    - scheme: slate 
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Home: index.md
  - Domain Structure: domain-structure/index.md
  - GitHub Pages: github_pages/index.md
  - Hashnode Blog: hashnode/index.md
  - Cloudflare Pages: cloudflare_pages/index.md
  - Discord domain verification: discord_verification/index.md
  - FAQ: faq/index.md
  - DanBot Hosting: dbh/index.md
  - Register using the Discord bot: discord/index.md
  - Delete your Domain: delete_domain/index.md 
  - Edit your Domain: edit_domain/index.md 
  - Replit: replit/index.md
  - Railway: railway/index.md
  - Other services: other/index.md
  - Dashboard: dashboard/index.md

